services:
  - type: web
    name: n8n
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    nodeVersion: 18.17.1
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: N8N_PORT
        value: 3000
      - key: PORT
        value: 3000
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_EDITOR_BASE_URL
        sync: false
